### ISSUE TITLE
Single model validation layer

### ISSUE THREAD

**Issue by charl** [dgeb/ember_rest_example#2]
Is there no way to avoid the double model validation (once by ember and once by ActiveRecord) when using ember with rails?

**Comment by dgeb** [comment]
There's no requirement that you provide client-side validation. Ember-rest checks if `validate()` is undefined on your `Ember.Resource` before calling it:

https://github.com/dgeb/ember_rest_example/blob/master/app/assets/javascripts/vendor/ember-rest.js#L139

If you're leaving validations to Rails, errors will bubble up from `jQuery.ajax()` to `Ember.Resource.saveResource()`. You'll need to make sure that your app handles the json error, similar to:

https://github.com/dgeb/ember_rest_example/blob/master/app/assets/javascripts/app/views/contacts/edit.js#L29-32

**Comment by charl** [comment]
Just wondering out loud: Wouldn't a generator(?) that translates rails validations into ember validations be useful? Client-side validations have their place and DRYing them up like this may be worthwhile if there is a one-to-one correlation.

**Comment by dgeb** [comment]
I'd have to agree - that would be quite useful. I wouldn't be surprised if someone eventually develops such a generator for use with ember-data, which has more detailed field and relationship definitions that closely mirror those in rails.
