### ISSUE TITLE
Does not work with older ember-rails version

### ISSUE THREAD

**Issue by phreax** [dgeb/ember_rest_example#3]
When using this example with ember-rails 0.2.4 which was installed by bundler, I get an ActionView::Template::Error. However it works fine, when using the current version from git (git://github.com/emberjs/ember-rails.git) which is version 0.3 as of writing this.

**Comment by dgeb** [comment]
Thanks for the heads up. I just pull down a fresh copy, performed a `bundle install`, and didn't have a problem myself. However, I'll leave this open in case anyone else does, and will update the project to the latest gem when it's released (which should be any day now).

**Comment by dgeb** [comment]
The example is now using the latest version of ember-rails. Let me know if you have any problems.
