### ISSUE TITLE
an error based on conversion nil into string

### ISSUE THREAD

**Issue by ekremkaraca** [dgeb/ember_rest_example#5]
Before beginning, thanks for this work. I've grabbed this example, made a bundle installation, migration, etc w/Rails 3.2.6. But when I was running this example, it gave error like this:
"can't convert nil into String
  (in /home/ekrem/workspace/ember_rest_example/app/assets/javascripts/app/templates/contacts/edit.handlebars)"

How can I fix?

**Comment by dgeb** [comment]
The issue you raised appears to be a problem in ember-rails 0.6.0 which needs investigation. In the mean time, I've updated this project to use rails 3.2.6 and fixed the version of ember-rails to 0.4.0.
