### ISSUE TITLE
App is empty

### ISSUE THREAD

**Issue by catsby** [dgeb/ember_rest_example#6]
I followed the instructions in the README, but this app doesn't seem to work. I get an empty page with an `<h1>Contacts</h1>` and that's it. I created a `Contact` with via the console and nothing shows up. Any ideas?

**Comment by dgeb** [comment]
I just did a fresh clone of the repo followed by:

```
bundle install
bundle exec rake db:migrate
rails s
```

... and the app is still working for me.

Are you see any errors in the rails or browser consoles?

**Comment by catsby** [comment]
Works fine now. Sorry to waste your time ¯(°_o)/¯
